remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
 author:
  name: "NehalAditya"
  avatar: "/assets/images/bio-photo.jpg" # a picture of you
  bio: "A short bio about yourself."
  location: "Your Location"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Nehal-aditya"

