name: Generate Sitemap

on:
  push:
    branches:
      - main # or your main branch name, e.g., master

jobs:
  build-and-generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This is crucial for the sitemap action to get the last commit date

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: 'https://your-username.github.io/your-repo-name/' # IMPORTANT: Replace with your actual website URL

      - name: Commit and push sitemap
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: Auto-generate and update sitemap.xml'
          # This action automatically commits the new sitemap file.
          # You may need to configure a token for this to work.
